// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: reelpulse.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "reelpulse";

export interface GetMovieTitleRequest {
  movieId: string;
}

export interface GetMovieTitleResponse {
  movieId: string;
  title: string;
  found: boolean;
}

function createBaseGetMovieTitleRequest(): GetMovieTitleRequest {
  return { movieId: "" };
}

export const GetMovieTitleRequest: MessageFns<GetMovieTitleRequest> = {
  encode(message: GetMovieTitleRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.movieId !== "") {
      writer.uint32(10).string(message.movieId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetMovieTitleRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetMovieTitleRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.movieId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetMovieTitleRequest {
    return {
      movieId: isSet(object.movieId)
        ? globalThis.String(object.movieId)
        : isSet(object.movie_id)
        ? globalThis.String(object.movie_id)
        : "",
    };
  },

  toJSON(message: GetMovieTitleRequest): unknown {
    const obj: any = {};
    if (message.movieId !== "") {
      obj.movieId = message.movieId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetMovieTitleRequest>, I>>(base?: I): GetMovieTitleRequest {
    return GetMovieTitleRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetMovieTitleRequest>, I>>(object: I): GetMovieTitleRequest {
    const message = createBaseGetMovieTitleRequest();
    message.movieId = object.movieId ?? "";
    return message;
  },
};

function createBaseGetMovieTitleResponse(): GetMovieTitleResponse {
  return { movieId: "", title: "", found: false };
}

export const GetMovieTitleResponse: MessageFns<GetMovieTitleResponse> = {
  encode(message: GetMovieTitleResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.movieId !== "") {
      writer.uint32(10).string(message.movieId);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.found !== false) {
      writer.uint32(24).bool(message.found);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetMovieTitleResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetMovieTitleResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.movieId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.found = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetMovieTitleResponse {
    return {
      movieId: isSet(object.movieId)
        ? globalThis.String(object.movieId)
        : isSet(object.movie_id)
        ? globalThis.String(object.movie_id)
        : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      found: isSet(object.found) ? globalThis.Boolean(object.found) : false,
    };
  },

  toJSON(message: GetMovieTitleResponse): unknown {
    const obj: any = {};
    if (message.movieId !== "") {
      obj.movieId = message.movieId;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.found !== false) {
      obj.found = message.found;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetMovieTitleResponse>, I>>(base?: I): GetMovieTitleResponse {
    return GetMovieTitleResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetMovieTitleResponse>, I>>(object: I): GetMovieTitleResponse {
    const message = createBaseGetMovieTitleResponse();
    message.movieId = object.movieId ?? "";
    message.title = object.title ?? "";
    message.found = object.found ?? false;
    return message;
  },
};

/**
 * MovieService: gRPC interface between Notification Service and Service A
 * Used by Notification Service to look up movie titles by ID
 */
export type MovieServiceService = typeof MovieServiceService;
export const MovieServiceService = {
  getMovieTitle: {
    path: "/reelpulse.MovieService/GetMovieTitle" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetMovieTitleRequest): Buffer => Buffer.from(GetMovieTitleRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetMovieTitleRequest => GetMovieTitleRequest.decode(value),
    responseSerialize: (value: GetMovieTitleResponse): Buffer =>
      Buffer.from(GetMovieTitleResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetMovieTitleResponse => GetMovieTitleResponse.decode(value),
  },
} as const;

export interface MovieServiceServer extends UntypedServiceImplementation {
  getMovieTitle: handleUnaryCall<GetMovieTitleRequest, GetMovieTitleResponse>;
}

export interface MovieServiceClient extends Client {
  getMovieTitle(
    request: GetMovieTitleRequest,
    callback: (error: ServiceError | null, response: GetMovieTitleResponse) => void,
  ): ClientUnaryCall;
  getMovieTitle(
    request: GetMovieTitleRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetMovieTitleResponse) => void,
  ): ClientUnaryCall;
  getMovieTitle(
    request: GetMovieTitleRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetMovieTitleResponse) => void,
  ): ClientUnaryCall;
}

export const MovieServiceClient = makeGenericClientConstructor(
  MovieServiceService,
  "reelpulse.MovieService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): MovieServiceClient;
  service: typeof MovieServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
